### ISSUE TITLE
File size limit

### ISSUE THREAD

**Issue by kuyoonjo** [achingbrain/mongoose-crate#18]
Is it possible to limit file size?
e.g.
```
attachment: {
 limit: 512k
},

attachments: {
  limit: 2m,
  array: true
}
```

**Comment by SOSANA** [comment]
```{ response: 'crickets' }```

It's this repo still active???

**Comment by achingbrain** [comment]
This repo is still active.  No, it's not possible without a PR.  I think you'd be better off using your web server or whatever to reject the upload with an appropriate HTTP response code before you hand the file off to mongoose-crate.

**Comment by SOSANA** [comment]
@achingbrain can we update the dependencies for this project? I kick started a project for a client yesterday, the want local storage now just for testing and in month or so s3 implmentations.

Yesterday, I tried to install both your project dependencies ```mongoose-crate``` which wouldn't download to my package.json, ```mongoose-crate``` but ```mongoose-crate-localfs``` did download, kept saying error for imagemagic dependency. I should be at my desk later if you want me to show you error msg.

is there something I am missing for gettting this to work?

**Comment by achingbrain** [comment]
Can you please post the error message?

**Comment by SOSANA** [comment]
@achingbrain 
```
C:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic>if not defined npm_config_node_gyp (node "C:\Users\zachs\AppData\Roaming\nvm\v6.6.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  apprentice.c
  apptype.c
  ascmagic.c
  cdf.c
  cdf_time.c
  compress.c
  der.c
  encoding.c
..\..\..\deps\libmagic\src\der.c(194): warning C4267: 'return': conversion fro m 'size_t' to 'uint32_t', possible loss of data [C:\dev\remote-projects\cute\c ute_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\compress.c(289): warning C4267: 'function': convers ion from 'size_t' to 'unsigned int', possible loss of data [C:\dev\remote-proj ects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxpr oj]
..\..\..\deps\libmagic\src\compress.c(356): warning C4267: 'function': convers ion from 'size_t' to 'unsigned int', possible loss of data [C:\dev\remote-proj ects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxpr oj]
..\..\..\deps\libmagic\src\compress.c(387): warning C4244: '=': conversion fro m 'ssize_t' to 'int', possible loss of data [C:\dev\remote-projects\cute\cute_ backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  fsmagic.c
..\..\..\deps\libmagic\src\der.c(254): warning C4267: '=': conversion from 'si ze_t' to 'int32_t', possible loss of data [C:\dev\remote-projects\cute\cute_ba ckend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\der.c(258): warning C4267: 'return': conversion fro m 'size_t' to 'int32_t', possible loss of data [C:\dev\remote-projects\cute\cu te_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\cdf_time.c(137): warning C4244: '=': conversion fro m 'time_t' to 'long', possible loss of data [C:\dev\remote-projects\cute\cute_ backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\cdf.c(799): warning C4267: 'return': conversion fro m 'size_t' to 'int', possible loss of data [C:\dev\remote-projects\cute\cute_b ackend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\apprentice.c(2977): warning C4267: 'function': conv ersion from 'size_t' to 'unsigned int', possible loss of data [C:\dev\remote-p rojects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vc xproj]
..\..\..\deps\libmagic\src\apprentice.c(3102): warning C4267: 'function': conv ersion from 'size_t' to 'unsigned int', possible loss of data [C:\dev\remote-p rojects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vc xproj]
  funcs.c
  is_tar.c
  magic.c
  print.c
  readcdf.c
  readelf.c
  softmagic.c
..\..\..\deps\libmagic\src\readelf.c(350): warning C4267: '+=': conversion fro m 'size_t' to 'off_t', possible loss of data [C:\dev\remote-projects\cute\cute _backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\readelf.c(861): warning C4244: 'return': conversion  from 'uint64_t' to 'off_t', possible loss of data [C:\dev\remote-projects\cut e\cute_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\readelf.c(1211): warning C4267: '+=': conversion fr om 'size_t' to 'off_t', possible loss of data [C:\dev\remote-projects\cute\cut e_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\readelf.c(1262): warning C4267: '=': conversion fro m 'size_t' to 'off_t', possible loss of data [C:\dev\remote-projects\cute\cute _backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\readelf.c(1348): warning C4244: '=': conversion fro m 'uint64_t' to 'off_t', possible loss of data [C:\dev\remote-projects\cute\cu te_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\readcdf.c(133): warning C4013: 'strcasestr' undefin ed; assuming extern returning int [C:\dev\remote-projects\cute\cute_backend\no de_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  fmtcheck.c
  asctime_r.c
  asprintf.c
..\..\..\deps\libmagic\src\readcdf.c(133): warning C4047: '!=': 'int' differs
in levels of indirection from 'void *' [C:\dev\remote-projects\cute\cute_backe nd\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\readelf.c(1453): warning C4267: '+=': conversion fr om 'size_t' to 'off_t', possible loss of data [C:\dev\remote-projects\cute\cut e_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\readcdf.c(239): warning C4133: 'function': incompat ible types - from 'long *' to 'const time_t *' [C:\dev\remote-projects\cute\cu te_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\softmagic.c(1186): warning C4267: '=': conversion f rom 'size_t' to 'uint32_t', possible loss of data [C:\dev\remote-projects\cute \cute_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  ctime_r.c
  dprintf.c
  getline.c
  gmtime_r.c
  localtime_r.c
  pread.c
  snprintf.c
  strcasestr.c
  strlcat.c
  strlcpy.c
  vasprintf.c
  win_delay_load_hook.c
..\..\..\deps\libmagic\src\pread.c(19): warning C4267: 'function': conversion
from 'size_t' to 'unsigned int', possible loss of data [C:\dev\remote-projects \cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Users\zachs\AppData\Roaming\nvm\v6.6.0\node_modules\npm\node_modules\node-g yp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefini tion; different type modifiers [C:\dev\remote-projects\cute\cute_backend\node_ modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(13
  4): note: see declaration of '__pfnDliNotifyHook2'
..\..\..\deps\libmagic\src\magic.c(514): warning C4267: 'function': conversion  from 'size_t' to 'unsigned int', possible loss of data [C:\dev\remote-project s\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  pcre_byte_order.c
  pcre_chartables.c
  pcre_compile.c
  pcre_config.c
  pcre_dfa_exec.c
  pcre_exec.c
  pcre_fullinfo.c
  pcre_get.c
..\..\..\..\deps\libmagic\pcre\pcre_dfa_exec.c(1662): warning C4146: unary min us operator applied to unsigned type, result still unsigned [C:\dev\remote-pro jects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre. vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_dfa_exec.c(1708): warning C4146: unary min us operator applied to unsigned type, result still unsigned [C:\dev\remote-pro jects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre. vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_dfa_exec.c(1752): warning C4146: unary min us operator applied to unsigned type, result still unsigned [C:\dev\remote-pro jects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre. vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_dfa_exec.c(1793): warning C4146: unary min us operator applied to unsigned type, result still unsigned [C:\dev\remote-pro jects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre. vcxproj]
  pcre_globals.c
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(4145): warning C4244: '+=': conv ersion from '__int64' to 'int', possible loss of data [C:\dev\remote-projects\ cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxpro j]
..\..\..\..\deps\libmagic\pcre\pcre_exec.c(656): warning C4244: 'initializing' : conversion from '__int64' to 'int', possible loss of data [C:\dev\remote-pro jects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre. vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(5250): warning C4244: 'initializ ing': conversion from '__int64' to 'int', possible loss of data [C:\dev\remote -projects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libp cre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(5251): warning C4244: 'initializ ing': conversion from '__int64' to 'int', possible loss of data [C:\dev\remote -projects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libp cre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(5332): warning C4244: 'initializ ing': conversion from '__int64' to 'int', possible loss of data [C:\dev\remote -projects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libp cre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(5333): warning C4244: 'initializ ing': conversion from '__int64' to 'int', possible loss of data [C:\dev\remote -projects\cute\cute_backend\node_modules\mmmagic\build\deps\libmagic\pcre\libp cre.vcxproj]
  pcre_jit_compile.c
  pcre_maketables.c
  pcre_newline.c
  pcre_ord2utf8.c
  pcre_refcount.c
  pcre_string_utils.c
  pcre_study.c
  pcre_tables.c
  pcre_ucd.c
  pcre_valid_utf8.c
  pcre_version.c
  pcre_xclass.c
  pcreposix.c
  win_delay_load_hook.c
C:\Users\zachs\AppData\Roaming\nvm\v6.6.0\node_modules\npm\node_modules\node-g yp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefini tion; different type modifiers [C:\dev\remote-projects\cute\cute_backend\node_ modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(13
  4): note: see declaration of '__pfnDliNotifyHook2'
c:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic\deps\libmagic\pc re\sljit\sljitNativeX86_64.c(388): warning C4244: '=': conversion from 'sljit_ sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\de ps\libmagic\pcre\pcre_jit_compile.c) [C:\dev\remote-projects\cute\cute_backend \node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
c:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic\deps\libmagic\pc re\sljit\sljitNativeX86_64.c(584): warning C4244: '=': conversion from 'sljit_ sw' to 'sljit_ub', possible loss of data (compiling source file ..\..\..\..\de ps\libmagic\pcre\pcre_jit_compile.c) [C:\dev\remote-projects\cute\cute_backend \node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
c:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic\deps\libmagic\pc re\sljit\sljitNativeX86_64.c(586): warning C4244: '=': conversion from 'sljit_ sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\de ps\libmagic\pcre\pcre_jit_compile.c) [C:\dev\remote-projects\cute\cute_backend \node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
c:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic\deps\libmagic\pc re\sljit\sljitNativeX86_64.c(593): warning C4244: '=': conversion from 'sljit_ sw' to 'sljit_ub', possible loss of data (compiling source file ..\..\..\..\de ps\libmagic\pcre\pcre_jit_compile.c) [C:\dev\remote-projects\cute\cute_backend \node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
c:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic\deps\libmagic\pc re\sljit\sljitNativeX86_64.c(599): warning C4244: '=': conversion from 'sljit_ sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\de ps\libmagic\pcre\pcre_jit_compile.c) [C:\dev\remote-projects\cute\cute_backend \node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
c:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic\deps\libmagic\pc re\sljit\sljitNativeX86_64.c(605): warning C4244: '=': conversion from 'sljit_ sw' to 'sljit_ub', possible loss of data (compiling source file ..\..\..\..\de ps\libmagic\pcre\pcre_jit_compile.c) [C:\dev\remote-projects\cute\cute_backend \node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
c:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic\deps\libmagic\pc re\sljit\sljitNativeX86_64.c(607): warning C4244: '=': conversion from 'sljit_ sw' to 'short', possible loss of data (compiling source file ..\..\..\..\deps\ libmagic\pcre\pcre_jit_compile.c) [C:\dev\remote-projects\cute\cute_backend\no de_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
c:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic\deps\libmagic\pc re\sljit\sljitNativeX86_64.c(609): warning C4244: '=': conversion from 'sljit_ sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\de ps\libmagic\pcre\pcre_jit_compile.c) [C:\dev\remote-projects\cute\cute_backend \node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
c:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic\deps\libmagic\pc re\sljit\sljitNativeX86_64.c(742): warning C4244: '=': conversion from 'sljit_ sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\de ps\libmagic\pcre\pcre_jit_compile.c) [C:\dev\remote-projects\cute\cute_backend \node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\zachs\AppData\Roaming\nvm\v6.6.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zachs\\AppData\\Roaming\\nvm\\v6.6.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\remote-projects\cute\cute_backend\node_modules\mmmagic
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
cute_backend@0.0.1 C:\dev\remote-projects\cute\cute_backend
+-- UNMET PEER DEPENDENCY eslint-plugin-import@2.0.0
`-- UNMET PEER DEPENDENCY eslint-plugin-react@^6.3.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-react@^6.3.0 but none was installed.
npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-S" "mongoose-crate"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! mmmagic@0.4.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.4.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:npm ERR!     npm bugs mmmagic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\remote-projects\cute\cute_backend\npm-debug.log
npm ERR! code 1
```
Something tells me if I install the depreciated imagemagic plugin you have for mongoose this will work but haven't tried to install it as I didn't think this was needed as a dependecy.

**Comment by achingbrain** [comment]
It looks like you're having problems installing the mmmagic dependency.  The error is:

```
C:\Users\zachs\AppData\Roaming\nvm\v6.6.0\node_modules\npm\node_modules\node-g yp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefini tion; different type modifiers [C:\dev\remote-projects\cute\cute_backend\node_ modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
```

A quick google reveals that [upgrading your copy of npm](https://github.com/nodejs/node-gyp/issues/972) may help.

Can you try that please?
